project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    search: true
    left: 
      - href: about.qmd
        text: Home
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
    right:
      - icon: github
        href: https://github.com
        aria-label: GitHub

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

